#!/usr/bin/env python3
"""
analyze_soak_test.py - Production-grade analysis tool for soak test results

Analyzes the metrics CSV generated by soak_test.sh and produces a
comprehensive report on memory usage, CPU usage, and throughput.

Usage:
    python3 analyze_soak_test.py <metrics_csv>

Example:
    python3 analyze_soak_test.py soak_logs/soak_metrics.csv
"""

import sys
import argparse
from typing import Tuple
from pathlib import Path

try:
    import pandas as pd
except ImportError:
    print("Error: pandas not found. Install with: pip install pandas", file=sys.stderr)
    sys.exit(1)


# Memory leak threshold in MB
LEAK_THRESHOLD_MB = 50


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Analyze soak test metrics CSV",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example:
  %(prog)s soak_logs/soak_metrics.csv
        """
    )
    parser.add_argument(
        "csv_file",
        type=Path,
        help="Path to soak_metrics.csv file"
    )
    parser.add_argument(
        "--leak-threshold",
        type=float,
        default=LEAK_THRESHOLD_MB,
        help=f"Memory leak threshold in MB (default: {LEAK_THRESHOLD_MB})"
    )
    return parser.parse_args()


def load_metrics(csv_path: Path) -> pd.DataFrame:
    """Load and validate metrics CSV file."""
    if not csv_path.exists():
        print(f"Error: File not found: {csv_path}", file=sys.stderr)
        sys.exit(1)
    
    try:
        df = pd.read_csv(csv_path)
    except Exception as e:
        print(f"Error reading CSV: {e}", file=sys.stderr)
        sys.exit(1)
    
    # Validate required columns
    required_cols = ["timestamp", "elapsed_sec", "recond_rss_mb", "recond_cpu_pct", "events_total"]
    missing_cols = [col for col in required_cols if col not in df.columns]
    if missing_cols:
        print(f"Error: Missing required columns: {missing_cols}", file=sys.stderr)
        sys.exit(1)
    
    if df.empty:
        print("Error: CSV file is empty", file=sys.stderr)
        sys.exit(1)
    
    return df


def analyze_memory(df: pd.DataFrame, leak_threshold: float) -> Tuple[int, int, int, int, str]:
    """
    Analyze memory usage statistics.
    
    Returns:
        Tuple of (initial_mb, final_mb, max_mb, leak_mb, status)
    """
    initial_mb = int(df["recond_rss_mb"].iloc[0])
    final_mb = int(df["recond_rss_mb"].iloc[-1])
    max_mb = int(df["recond_rss_mb"].max())
    leak_mb = final_mb - initial_mb
    
    status = "PASS" if leak_mb < leak_threshold else "FAIL"
    
    return initial_mb, final_mb, max_mb, leak_mb, status


def analyze_cpu(df: pd.DataFrame) -> Tuple[float, float]:
    """
    Analyze CPU usage statistics.
    
    Returns:
        Tuple of (mean_pct, max_pct)
    """
    mean_pct = float(df["recond_cpu_pct"].mean())
    max_pct = float(df["recond_cpu_pct"].max())
    
    return mean_pct, max_pct


def analyze_throughput(df: pd.DataFrame) -> Tuple[int, float, float]:
    """
    Analyze throughput statistics.
    
    Returns:
        Tuple of (total_events, duration_hours, rate_per_sec)
    """
    total_events = int(df["events_total"].iloc[-1])
    duration_sec = int(df["elapsed_sec"].iloc[-1])
    duration_hours = duration_sec / 3600.0
    
    # Calculate effective rate
    rate_per_sec = 0.0
    if duration_sec > 0:
        rate_per_sec = total_events / duration_sec
    
    return total_events, duration_hours, rate_per_sec


def format_large_number(n: int) -> str:
    """Format large numbers with comma separators."""
    return f"{n:,}"


def print_report(
    initial_mb: int,
    final_mb: int,
    max_mb: int,
    leak_mb: int,
    mem_status: str,
    mean_cpu: float,
    max_cpu: float,
    total_events: int,
    duration_hours: float,
    rate_per_sec: float,
    leak_threshold: float
) -> None:
    """Print formatted analysis report."""
    
    print()
    print("=" * 60)
    print(f"Soak Test Analysis (duration: {duration_hours:.1f} hours)")
    print("=" * 60)
    print()
    
    print("Memory Usage:")
    print(f"  Initial: {initial_mb} MB")
    print(f"  Final:   {final_mb} MB")
    print(f"  Max:     {max_mb} MB")
    leak_sign = "+" if leak_mb >= 0 else ""
    print(f"  Leak:    {leak_sign}{leak_mb} MB")
    print()
    
    print("CPU Usage:")
    print(f"  Mean: {mean_cpu:.1f}%")
    print(f"  Max:  {max_cpu:.1f}%")
    print()
    
    print("Throughput:")
    print(f"  Total:    {format_large_number(total_events)} events")
    print(f"  Duration: {duration_hours:.1f} hours")
    print(f"  Rate:     {rate_per_sec:,.0f} orders/sec")
    print()
    
    # Pass/Fail status
    if mem_status == "PASS":
        print(f"✅ PASS: No significant memory leak (threshold: {leak_threshold} MB)")
    else:
        print(f"❌ FAIL: Memory leak detected (leak: {leak_mb} MB, threshold: {leak_threshold} MB)")
    print()
    
    print("=" * 60)
    print()


def main() -> int:
    """Main entry point."""
    args = parse_args()
    
    # Load metrics
    df = load_metrics(args.csv_file)
    
    # Perform analysis
    initial_mb, final_mb, max_mb, leak_mb, mem_status = analyze_memory(df, args.leak_threshold)
    mean_cpu, max_cpu = analyze_cpu(df)
    total_events, duration_hours, rate_per_sec = analyze_throughput(df)
    
    # Print report
    print_report(
        initial_mb, final_mb, max_mb, leak_mb, mem_status,
        mean_cpu, max_cpu,
        total_events, duration_hours, rate_per_sec,
        args.leak_threshold
    )
    
    # Exit with appropriate code
    return 0 if mem_status == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
