#!/usr/bin/env python3
"""
analyze_soak_test.py - Production-grade analysis tool for soak test results

Analyzes the metrics CSV generated by soak_test.sh and produces a
comprehensive report on memory usage, CPU usage, and throughput.

Usage:
    python3 analyze_soak_test.py <metrics_csv>

Example:
    python3 analyze_soak_test.py soak_logs/soak_metrics.csv
"""

import sys
import argparse
from typing import Tuple
from pathlib import Path

try:
    import pandas as pd
except ImportError:
    print("Error: pandas not found. Install with: pip install pandas", file=sys.stderr)
    sys.exit(1)


# Memory leak threshold in MB/hour (FX-7064)
LEAK_THRESHOLD_MB_PER_HOUR = 10


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Analyze soak test metrics CSV",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example:
  %(prog)s soak_logs/soak_metrics.csv
        """
    )
    parser.add_argument(
        "csv_file",
        type=Path,
        help="Path to soak_metrics.csv file"
    )
    parser.add_argument(
        "--leak-threshold",
        type=float,
        default=LEAK_THRESHOLD_MB_PER_HOUR,
        help=f"Memory leak threshold in MB/hour (default: {LEAK_THRESHOLD_MB_PER_HOUR})"
    )
    parser.add_argument(
        "--recond-log",
        type=Path,
        help="Path to reconciler log file (optional, for arena metrics)"
    )
    return parser.parse_args()


def load_metrics(csv_path: Path) -> pd.DataFrame:
    """Load and validate metrics CSV file."""
    if not csv_path.exists():
        print(f"Error: File not found: {csv_path}", file=sys.stderr)
        sys.exit(1)
    
    try:
        df = pd.read_csv(csv_path)
    except Exception as e:
        print(f"Error reading CSV: {e}", file=sys.stderr)
        sys.exit(1)
    
    # Validate required columns (support both old and new CSV formats)
    required_cols = ["elapsed_sec", "recond_rss_mb", "recond_cpu_pct"]
    
    # For events_total, check if we have the new format (internal_events, dropcopy_events)
    # or old format (events_total)
    if "events_total" not in df.columns:
        if "internal_events" in df.columns and "dropcopy_events" in df.columns:
            # New format - calculate events_total
            df["events_total"] = df["internal_events"] + df["dropcopy_events"]
        else:
            print("Error: Missing event count columns (need either 'events_total' or 'internal_events' + 'dropcopy_events')", file=sys.stderr)
            sys.exit(1)
    
    missing_cols = [col for col in required_cols if col not in df.columns]
    if missing_cols:
        print(f"Error: Missing required columns: {missing_cols}", file=sys.stderr)
        sys.exit(1)
    
    if df.empty:
        print("Error: CSV file is empty", file=sys.stderr)
        sys.exit(1)
    
    return df


def analyze_memory(df: pd.DataFrame, leak_threshold: float) -> Tuple[int, int, int, int, str]:
    """
    Analyze memory usage statistics.
    
    Returns:
        Tuple of (initial_mb, final_mb, max_mb, leak_mb, status)
    """
    initial_mb = int(df["recond_rss_mb"].iloc[0])
    final_mb = int(df["recond_rss_mb"].iloc[-1])
    max_mb = int(df["recond_rss_mb"].max())
    leak_mb = final_mb - initial_mb
    
    # FX-7064: Scale threshold by duration to enforce consistent leak rate (MB/hour)
    # leak_threshold represents the acceptable leak rate in MB/hour
    duration_hours = df["elapsed_sec"].iloc[-1] / 3600.0
    adjusted_threshold = leak_threshold * duration_hours
    
    status = "PASS" if leak_mb < adjusted_threshold else "FAIL"
    
    return initial_mb, final_mb, max_mb, leak_mb, status


def analyze_cpu(df: pd.DataFrame) -> Tuple[float, float]:
    """
    Analyze CPU usage statistics.
    
    Returns:
        Tuple of (mean_pct, max_pct)
    """
    mean_pct = float(df["recond_cpu_pct"].mean())
    max_pct = float(df["recond_cpu_pct"].max())
    
    return mean_pct, max_pct


def analyze_throughput(df: pd.DataFrame) -> Tuple[int, float, float]:
    """
    Analyze throughput statistics.
    
    Returns:
        Tuple of (total_events, duration_hours, rate_per_sec)
    """
    total_events = int(df["events_total"].iloc[-1])
    duration_sec = int(df["elapsed_sec"].iloc[-1])
    duration_hours = duration_sec / 3600.0
    
    # Calculate effective rate
    rate_per_sec = 0.0
    if duration_sec > 0:
        rate_per_sec = total_events / duration_sec
    
    return total_events, duration_hours, rate_per_sec


def parse_arena_metrics(log_path: Path) -> Tuple[int, int, int, int]:
    """
    Parse arena metrics from reconciler log file.
    
    Returns:
        Tuple of (arena_resets, arena_reset_deferred, arena_bytes_used, arena_bytes_capacity)
        Returns (0, 0, 0, 0) if log file not provided or metrics not found.
    """
    if not log_path or not log_path.exists():
        return 0, 0, 0, 0
    
    import re
    
    try:
        with open(log_path, 'r') as f:
            # Read last 5000 lines to find the final reconciler stats
            lines = f.readlines()
            last_lines = lines[-5000:] if len(lines) > 5000 else lines
            
            # Find the last line with arena metrics
            for line in reversed(last_lines):
                if "arena_resets=" in line:
                    # Parse: arena_resets=X arena_reset_deferred=Y arena_bytes_used=Z arena_bytes_capacity=W
                    match_resets = re.search(r'arena_resets=(\d+)', line)
                    match_deferred = re.search(r'arena_reset_deferred=(\d+)', line)
                    match_used = re.search(r'arena_bytes_used=(\d+)', line)
                    match_capacity = re.search(r'arena_bytes_capacity=(\d+)', line)
                    
                    if match_resets and match_deferred and match_used and match_capacity:
                        return (
                            int(match_resets.group(1)),
                            int(match_deferred.group(1)),
                            int(match_used.group(1)),
                            int(match_capacity.group(1))
                        )
    except Exception as e:
        print(f"Warning: Failed to parse arena metrics: {e}", file=sys.stderr)
    
    return 0, 0, 0, 0


def format_large_number(n: int) -> str:
    """Format large numbers with comma separators."""
    return f"{n:,}"


def print_report(
    initial_mb: int,
    final_mb: int,
    max_mb: int,
    leak_mb: int,
    mem_status: str,
    mean_cpu: float,
    max_cpu: float,
    total_events: int,
    duration_hours: float,
    rate_per_sec: float,
    leak_threshold: float,
    arena_resets: int = 0,
    arena_reset_deferred: int = 0,
    arena_bytes_used: int = 0,
    arena_bytes_capacity: int = 0
) -> None:
    """Print formatted analysis report."""
    
    print()
    print("=" * 60)
    print(f"Soak Test Analysis (duration: {duration_hours:.3f} hours)")
    print("=" * 60)
    print()
    
    print("Memory Usage:")
    print(f"  Initial: {initial_mb} MB")
    print(f"  Final:   {final_mb} MB")
    print(f"  Max:     {max_mb} MB")
    leak_sign = "+" if leak_mb >= 0 else ""
    print(f"  Leak:    {leak_sign}{leak_mb} MB")
    
    # FX-7064: Calculate and display memory leak rate
    if duration_hours > 0:
        leak_rate_per_hour = leak_mb / duration_hours
        print(f"  Leak Rate: {leak_rate_per_hour:.1f} MB/hour")
    print()
    
    # FX-7064: Display arena metrics if available
    if arena_resets > 0 or arena_reset_deferred > 0 or arena_bytes_capacity > 0:
        print("Arena Memory Management (FX-7064):")
        print(f"  Resets:         {format_large_number(arena_resets)}")
        print(f"  Deferred:       {format_large_number(arena_reset_deferred)}")
        if arena_bytes_capacity > 0:
            arena_mb_used = arena_bytes_used / (1024 * 1024)
            arena_mb_capacity = arena_bytes_capacity / (1024 * 1024)
            utilization_pct = (arena_bytes_used / arena_bytes_capacity * 100) if arena_bytes_capacity > 0 else 0
            print(f"  Used:           {arena_mb_used:.1f} MB")
            print(f"  Capacity:       {arena_mb_capacity:.1f} MB")
            print(f"  Utilization:    {utilization_pct:.1f}%")
        print()
    
    print("CPU Usage:")
    print(f"  Mean: {mean_cpu:.1f}%")
    print(f"  Max:  {max_cpu:.1f}%")
    print()
    
    print("Throughput:")
    print(f"  Total:    {format_large_number(total_events)} events")
    print(f"  Duration: {duration_hours:.3f} hours")
    print(f"  Rate:     {rate_per_sec:,.0f} events/sec")
    print()
    
    # Pass/Fail status with adjusted threshold calculation
    adjusted_threshold = leak_threshold * duration_hours
    if mem_status == "PASS":
        print(f"✅ PASS: No significant memory leak")
        print(f"   Threshold: {leak_threshold} MB/hour ({adjusted_threshold:.1f} MB for {duration_hours:.1f} hours)")
    else:
        print(f"❌ FAIL: Memory leak detected")
        print(f"   Leak: {leak_mb} MB")
        print(f"   Threshold: {leak_threshold} MB/hour ({adjusted_threshold:.1f} MB for {duration_hours:.1f} hours)")
    print()
    
    print("=" * 60)
    print()


def main() -> int:
    """Main entry point."""
    args = parse_args()
    
    # Load metrics
    df = load_metrics(args.csv_file)
    
    # Perform analysis
    initial_mb, final_mb, max_mb, leak_mb, mem_status = analyze_memory(df, args.leak_threshold)
    mean_cpu, max_cpu = analyze_cpu(df)
    total_events, duration_hours, rate_per_sec = analyze_throughput(df)
    
    # FX-7064: Parse arena metrics from reconciler log if provided
    arena_resets, arena_reset_deferred, arena_bytes_used, arena_bytes_capacity = 0, 0, 0, 0
    if args.recond_log:
        arena_resets, arena_reset_deferred, arena_bytes_used, arena_bytes_capacity = parse_arena_metrics(args.recond_log)
    
    # Print report
    print_report(
        initial_mb, final_mb, max_mb, leak_mb, mem_status,
        mean_cpu, max_cpu,
        total_events, duration_hours, rate_per_sec,
        args.leak_threshold,
        arena_resets, arena_reset_deferred, arena_bytes_used, arena_bytes_capacity
    )
    
    # Exit with appropriate code
    return 0 if mem_status == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
